### PR TITLE
Upgrade to v81

### PR DESCRIPTION
**Pull request by LottePitcher**
@leekelleher @MMasey @emmaburstow this PR upgrades the project to use Umbraco 8.1. All seems to still work!  You'll need to upgrade your own test website to be on v8.1 too. 

I also snuck in a tweak to the view to get rid of the empty space at the bottom of the screen that would be where the save button would be, were we putting it there, but we're not. Sorry, terrible practice to do it on same PR I'm sure.

@leekelleher the upgrade removed the '<Private>False</Private>' from my csproj.  I'm not sure there is a difference between this being false, and not being there at all.  Do you?

### CODE REVIEW

**Review by leekelleher — APPROVED** [review]
Hi, I am Lee Kelleher 👋 and I approve this PR! ✌️ 

---

re: the `<Private>False</Private>` tags - this is the flag for the "Copy Local" property for assembly references. This option is whether you want a specific assembly to be copied to the /bin folder when the project is compiled.

By default in VS this is set to True - it makes total sense when building an application. But since we're building a library, that we're XCOPY'ing our assembly to elsewhere for testing, by setting "Copy Local" to false, we don't need to clutter our /bin folder with additional DLLs, etc.  Also this mitigates against anyone accidentally overwriting existing Umbraco DLLs, e.g. if we target v8.1 assemblies, but our test project was 8.2, then the DLLs could accidentally revert to v8.1, causing all sorts of headaches.

Hope this hasn't been a too long waffley explanation.

**Comment by LottePitcher** [comment]
@leekelleher makes sense and thanks for putting them back in!

**Comment by leekelleher** [comment]
Shall we merge this one in?

**Comment by emmaburstow** [comment]
I'm happy for that to happen 💃

**Comment by LottePitcher** [comment]
Fine my me!  As the creator of the PR of course it can't be me that does  ;-)

**Comment by leekelleher** [comment]
@emmaburstow Push the button!!! 😁

**Comment by emmaburstow** [comment]
Done :) But now I have the Sugababes stuck in my head...

**Pull request merged**
